[client]
name = "ReAct"
prompt_template = "./react-template.txt"
game_name = "zork1"
maximum_step = 250
missing_tool_call_threshold = 5
history_max_length = 10
max_branch_per_node = 1

[config]
recursion_limit = 1200

[execute]
iterations = 10
