[client]
name = "TReAct"
prompt_template = "./treact-template.txt"
game_name = "zork1"
maximum_step = 250
len_tool_calls_out_of_range_threshold = 5
history_max_length = 10
max_branch_per_node = 3
min_tool_calls = 1
max_tool_calls = 15

[config]
recursion_limit = 2500

[execute]
iterations = 10
